### PR TITLE
hacks for tests on windows

### PR DESCRIPTION
**Pull request by sroylance**
With these changes, all tests pass for me on windows 10 running "go version go1.9.4 windows/amd64"

### CODE REVIEW

**Comment by sroylance** [comment]
@k8s-ci-robot please re-check the CLA

**Comment by justinsb** [comment]
So happy to see this - thank you!  I'd love to get windows support working in kops 1.10 - which we have targeted for the end of April.  But I'm also wary of introducing this this late into the 1.9 cycle, so I'm targeting for 1.10 and hopefully we'll cut the branches next week and we can get this going :-)

**Comment by chrislovecnm** [comment]
@jordansissel ptal

**Comment by jordansissel** [comment]
Multiple failures on my workstation (Windows 10):

Here's the full output from `go test`:

<details>
<summary><code>PS D:\build\kops> go test -v $(cat hack/.packages)</code></summary>

```
?       k8s.io/kops     [no test files]
# k8s.io/kops/upup/pkg/fi/nodeup/nodetasks
D:\gopath\src\k8s.io\kops\upup\pkg\fi\nodeup\nodetasks\file.go:157:26: undefined: syscall.Stat_t
D:\gopath\src\k8s.io\kops\upup\pkg\fi\nodeup\nodetasks\file.go:168:26: undefined: syscall.Stat_t
D:\gopath\src\k8s.io\kops\upup\pkg\fi\nodeup\nodetasks\file.go:285:24: undefined: fi.EnsureFileOwner
# k8s.io/kops/upup/pkg/fi/nodeup/nodetasks
D:\gopath\src\k8s.io\kops\upup\pkg\fi\nodeup\nodetasks\file.go:157:26: undefined: syscall.Stat_t
D:\gopath\src\k8s.io\kops\upup\pkg\fi\nodeup\nodetasks\file.go:168:26: undefined: syscall.Stat_t
D:\gopath\src\k8s.io\kops\upup\pkg\fi\nodeup\nodetasks\file.go:285:24: undefined: fi.EnsureFileOwner
?       k8s.io/kops/channels/cmd/channels       [no test files]
?       k8s.io/kops/channels/pkg/api    [no test files]
=== RUN   Test_Filtering
--- PASS: Test_Filtering (0.00s)
=== RUN   Test_Replacement
--- PASS: Test_Replacement (0.00s)
PASS
ok      k8s.io/kops/channels/pkg/channels       4.219s
?       k8s.io/kops/channels/pkg/cmd    [no test files]
?       k8s.io/kops/cloudmock/aws/mockautoscaling       [no test files]
?       k8s.io/kops/cloudmock/aws/mockec2       [no test files]
?       k8s.io/kops/cloudmock/aws/mockelb       [no test files]
?       k8s.io/kops/cloudmock/aws/mockiam       [no test files]
?       k8s.io/kops/cloudmock/aws/mockroute53   [no test files]
=== RUN   TestCreateClusterMinimal
--- FAIL: TestCreateClusterMinimal (0.05s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestCreateClusterOverride
--- FAIL: TestCreateClusterOverride (0.05s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestCreateClusterComplex
--- FAIL: TestCreateClusterComplex (0.04s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestCreateClusterHA
--- FAIL: TestCreateClusterHA (0.05s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestCreateClusterHAGCE
--- FAIL: TestCreateClusterHAGCE (0.03s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestCreateClusterHASharedZones
--- FAIL: TestCreateClusterHASharedZones (0.04s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestCreateClusterPrivate
--- FAIL: TestCreateClusterPrivate (0.05s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestCreateClusterWithNGWSpecified
--- FAIL: TestCreateClusterWithNGWSpecified (0.03s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestCreateClusterSharedVPC
--- FAIL: TestCreateClusterSharedVPC (0.03s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestCreateClusterSharedSubnets
--- FAIL: TestCreateClusterSharedSubnets (0.03s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestCreateClusterSharedSubnetsVpcLookup
--- FAIL: TestCreateClusterSharedSubnetsVpcLookup (0.09s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestCreateClusterPrivateSharedSubnets
--- FAIL: TestCreateClusterPrivateSharedSubnets (0.06s)
        create_cluster_integration_test.go:189: error running create cluster: invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestParseCloudLabels
--- PASS: TestParseCloudLabels (0.00s)
=== RUN   TestRemoveSharedPrefix
--- PASS: TestRemoveSharedPrefix (0.00s)
=== RUN   TestConfirmation
--- PASS: TestConfirmation (0.00s)
=== RUN   TestMinimal
--- FAIL: TestMinimal (0.06s)
        integration_test.go:223: error running update cluster "minimal.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestHA
--- FAIL: TestHA (0.01s)
        integration_test.go:223: error running update cluster "ha.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestHighAvailabilityGCE
--- FAIL: TestHighAvailabilityGCE (0.01s)
        integration_test.go:223: error running update cluster "ha-gce.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestComplex
--- FAIL: TestComplex (0.01s)
        integration_test.go:223: error running update cluster "complex.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestMinimalCloudformation
--- FAIL: TestMinimalCloudformation (0.01s)
        integration_test.go:485: error running update cluster "minimal.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestAdditionalUserData
--- FAIL: TestAdditionalUserData (0.01s)
        integration_test.go:485: error running update cluster "additionaluserdata.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestBastionAdditionalUserData
--- FAIL: TestBastionAdditionalUserData (0.01s)
        integration_test.go:223: error running update cluster "bastionuserdata.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestMinimal_141
--- FAIL: TestMinimal_141 (0.01s)
        integration_test.go:223: error running update cluster "minimal-141.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestPrivateWeave
--- FAIL: TestPrivateWeave (0.01s)
        integration_test.go:223: error running update cluster "privateweave.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestPrivateFlannel
--- FAIL: TestPrivateFlannel (0.01s)
        integration_test.go:223: error running update cluster "privateflannel.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestPrivateCalico
--- FAIL: TestPrivateCalico (0.01s)
        integration_test.go:223: error running update cluster "privatecalico.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestPrivateCanal
--- FAIL: TestPrivateCanal (0.01s)
        integration_test.go:223: error running update cluster "privatecanal.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestPrivateKopeio
--- FAIL: TestPrivateKopeio (0.01s)
        integration_test.go:223: error running update cluster "privatekopeio.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestPrivateSharedSubnet
--- FAIL: TestPrivateSharedSubnet (0.01s)
        integration_test.go:223: error running update cluster "private-shared-subnet.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestPrivateDns1
--- FAIL: TestPrivateDns1 (0.01s)
        integration_test.go:223: error running update cluster "privatedns1.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestPrivateDns2
--- FAIL: TestPrivateDns2 (0.01s)
        integration_test.go:223: error running update cluster "privatedns2.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestSharedSubnet
--- FAIL: TestSharedSubnet (0.01s)
        integration_test.go:223: error running update cluster "sharedsubnet.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestSharedVPC
--- FAIL: TestSharedVPC (0.01s)
        integration_test.go:223: error running update cluster "sharedvpc.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestPhaseNetwork
--- FAIL: TestPhaseNetwork (0.01s)
        integration_test.go:223: error running update cluster "lifecyclephases.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestPhaseIAM
--- SKIP: TestPhaseIAM (0.00s)
        integration_test.go:158: unable to test w/o allowing failed validation
=== RUN   TestPhaseCluster
--- SKIP: TestPhaseCluster (0.00s)
        integration_test.go:165: unable to test w/o allowing failed validation
=== RUN   TestLifecycleMinimal
--- FAIL: TestLifecycleMinimal (0.01s)
        lifecycle_integration_test.go:155: error running update cluster "minimal.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestLifecyclePrivateCalico
--- FAIL: TestLifecyclePrivateCalico (0.01s)
        lifecycle_integration_test.go:155: error running update cluster "privatecalico.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestLifecyclePrivateKopeio
--- FAIL: TestLifecyclePrivateKopeio (0.00s)
        lifecycle_integration_test.go:155: error running update cluster "privatekopeio.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestLifecycleSharedVPC
--- FAIL: TestLifecycleSharedVPC (0.00s)
        lifecycle_integration_test.go:155: error running update cluster "sharedvpc.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestLifecycleSharedSubnet
--- FAIL: TestLifecycleSharedSubnet (0.00s)
        lifecycle_integration_test.go:155: error running update cluster "sharedsubnet.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
=== RUN   TestLifecyclePrivateSharedSubnet
--- FAIL: TestLifecyclePrivateSharedSubnet (0.00s)
        lifecycle_integration_test.go:155: error running update cluster "private-shared-subnet.example.com": invalid base channel location: "file://D:\\gopath\\src\\k8s.io\\kops\\channels/"
FAIL
FAIL    k8s.io/kops/cmd/kops    2.062s
?       k8s.io/kops/cmd/kops/util       [no test files]
?       k8s.io/kops/cmd/kops-server     [no test files]
```
</details>

**Comment by sroylance** [comment]
That's the expected output.  I have another branch to address the issues the tests have running on windows.

**Comment by chrislovecnm** [comment]
@sroylance did you want to push another PR based on this one to fix all the problems?  How do you want to proceed?

**Comment by justinsb** [comment]
I've (finally) got a machine up to test this - thanks @sroylance 

/approve

/lgtm
